// German texts ("du", short). Typed as the English shape: a key missing here
// fails the type check. Product names (Farcall, Worktree, Branch) stay as they are.
import { forms, plural } from "./helpers.ts";
import type { Strings } from "./en.ts";

export const de: Strings = {
  workerWorkspace: {
    branch: (branch: string) => `Worktree-Branch: ${branch}`,
    folder: (name: string) => `Arbeitsordner: ${name} (aus dem Aufgabenpfad, Branch unbekannt)`,
    detached: (name: string) => `Worktree: ${name} (kein Branch)`,
  },
  list: {
    title: "Maschine → Projekt",
    description: "Gespräche nach Maschine gruppiert, darunter nach Projekt.",
    label: "Gespräche nach Maschine",
    loading: "Gespräche werden geladen…",
    loadError: "Gespräche konnten nicht geladen werden.",
    empty: "Noch keine Gespräche.",
  },
  groups: {
    personal: "Gespräche",
    unknownProject: "Unbekanntes Projekt",
    noMachine: "Keine Maschine",
    pinned: "Angepinnt",
    inactive: "Inaktiv",
  },
  status: {
    agentWorking: "Agent arbeitet",
    subThreadAgentWorking: "Agent eines Untergesprächs arbeitet",
    subThreadAttention: (kind) =>
      `Ein Untergespräch ${kind === "waiting" ? "wartet auf deine Eingabe" : kind === "failed" ? "ist fehlgeschlagen" : "ist fertig"}`,
    attention: { waiting: "Wartet auf deine Eingabe", failed: "Fehlgeschlagen", done: "Fertig" },
    worktree: "Worktree",
    worktreeTitle: "Git-Worktree",
    activity: (count, one, many) => `${count} ${plural(count, one, many)} aktiv`,
  },
  activity: {
    backgroundAgents: forms("Unteragent", "Unteragenten"),
    backgroundCommands: forms("Hintergrundbefehl", "Hintergrundbefehle"),
    workflows: forms("Workflow", "Workflows"),
    planMode: forms("Plan", "Pläne"),
    goals: forms("Ziel", "Ziele"),
  },
  subThreads: {
    count: (count) => `${count} ${plural(count, "Untergespräch", "Untergespräche")}`,
    toggle: (collapsed, count) =>
      `${collapsed ? "Anzeigen:" : "Ausblenden:"} ${count} ${plural(count, "Untergespräch", "Untergespräche")}`,
  },
  row: {
    actions: "Gesprächsaktionen",
    titleInput: "Gesprächstitel",
    archive: "Archivieren",
    archiveThread: "Gespräch archivieren",
    branchTitle: (branch, isWorktree) => (isWorktree ? `${branch} (Worktree)` : branch),
    newThreadIn: (project, machine) => `Neues Gespräch in ${project} auf ${machine}`,
  },
  menu: {
    split: "In geteilter Ansicht öffnen",
    rename: "Umbenennen",
    pin: "Anpinnen",
    unpin: "Lösen",
    markRead: "Als gelesen markieren",
    markUnread: "Als ungelesen markieren",
    markActive: "Aktiv markieren",
    markInactive: "Inaktiv markieren",
    markProjectActive: "Projekt aktiv markieren",
    markProjectInactive: "Projekt inaktiv markieren",
    markAllActive: "Alle aktiv markieren",
    archive: "Archivieren",
    delete: "Löschen…",
  },
  farcall: {
    tasksUnder: (title) => `Farcall-Aufgaben unter ${title}`,
    done: "Erledigt",
    refreshError: "Farcall-Aufgaben konnten nicht aktualisiert werden.",
    callTimeHint: "Verstrichene Zeit des Tool-Aufrufs laut BB-Ereignissen, nicht die gemessene Laufzeit des Workers",
    modelUnknown: "Modell unbekannt",
    status: {
      open: { label: "Aufruf offen", short: "offen" },
      unknown: { label: "Ergebnis unbekannt", short: "unbekannt" },
      completed: { label: "Abgeschlossen", short: "fertig" },
      failed: { label: "Fehlgeschlagen", short: "Fehler" },
      spawnError: { label: "Start fehlgeschlagen", short: "Fehler" },
      evidenceError: { label: "Fehler bei den Nachweisen", short: "Fehler" },
      timeout: { label: "Zeitüberschreitung", short: "Zeitlimit" },
      cancelled: { label: "Abgebrochen", short: "abgebrochen" },
      interrupted: { label: "Unterbrochen", short: "unterbrochen" },
      notStarted: { label: "Nicht gestartet", short: "nicht gestartet" },
    },
    duration: {
      unavailable: "Zeit nicht verfügbar",
      lessThanMinute: "<1 Min.",
      minutes: (minutes) => `${minutes} Min.`,
      hoursMinutes: (hours, minutes) => `${hours} Std. ${minutes} Min.`,
      daysHours: (days, hours) => `${days} T. ${hours} Std.`,
    },
  },
  tags: {
    sectionTitle: "Titel-Tags",
    sectionDescription: "Farben für [Tag]-Präfixe in Gesprächstiteln.",
    loading: "Tags werden geladen…",
    loadError: (error) => `Tags konnten nicht geladen werden: ${error}`,
    tagName: "Tag-Name",
    introStart: "Beginne einen Gesprächstitel mit ",
    introExampleTag: "[Tag]",
    introMiddle: " für eine farbige Markierung in der Sidebar, z. B. ",
    introExampleTitle: "[Bug] Anmeldung schlägt fehl",
    introEnd:
      ". Hier aufgeführte Tags verwenden die gewählte Farbe; andere erhalten automatisch eine Farbe. Groß- und Kleinschreibung spielen keine Rolle.",
    empty: "Noch keine Tag-Farben.",
    duplicate: (tag) => `„${tag}“ ist doppelt vorhanden; nur der erste Eintrag wird verwendet.`,
    add: "Tag hinzufügen",
    save: "Speichern",
    saving: "Wird gespeichert…",
    discard: "Verwerfen",
    saved: "Gespeichert. Offene Fenster werden sofort aktualisiert.",
    saveError: (error) => `Speichern fehlgeschlagen: ${error}`,
    remove: (tag) => `${tag || "Tag"} entfernen`,
    colorFor: (tag) => `Farbe für ${tag || "neuen Tag"}`,
    colors: {
      red: "Rot",
      orange: "Orange",
      amber: "Bernstein",
      green: "Grün",
      teal: "Türkis",
      blue: "Blau",
      violet: "Violett",
      pink: "Pink",
      gray: "Grau",
    },
  },
};
